# Generated by Django 5.1.4 on 2025-01-13 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customertransaction',
            table='customer_transactions',
        ),
        migrations.AlterModelTable(
            name='paymentplan',
            table='payment_plans',
        ),
    ]
