# Generated by Django 5.1.4 on 2025-01-13 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0002_alter_customertransaction_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectornote',
            name='note_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='collectornote',
            name='note_title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
