# Generated by Django 5.1.4 on 2025-01-14 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0004_alter_collectornote_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectornote',
            name='note_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='collectornote',
            name='note_title',
            field=models.CharField(max_length=50),
        ),
    ]
